default:
  exp_name: "blockwords"
  dir_empiric: "./data/prolific/blockwords"
  generate_utterances: false
  seed_tables: 202008
  save: true
  cost_conditional: 0
  alpha: 3
  theta: 0.7
  verbose: true
  cns: !expr c("A implies C", "C implies A", "A implies -C", "C implies -A", "A || C")
  packages:  !expr c(here("model", "webppl-model", "node_modules", "conditionalsHelpers"),
                     here("model", "webppl-model", "node_modules", "conditionalsDefault"))
  model_path: !expr here("model", "webppl-model", "default-model", "default-model.wppl")
  #seed_webppl: !expr as.numeric(Sys.time())
  seed_webppl: 123467
  vars: !expr c("A", "C")
  bias: "none"

# only add new variables, since if more than two config-ids are loaded
# default value is taken again if it does not appear in a later loaded config-id,
# although it had been overwritten in a previously loaded config-id
tables_model_filtered_augmented:
  dir_empiric: "./data/prolific/blockwords/filtered_data"
  tables_empiric: "./model/data/tables-model-empirical-filtered-with-augmented-toWPPL.rds"
  target_dir: "./model/results/tables-model-filtered-augmented"
  utts_path: "./model/data/utterances-model-tables.rds"
  tables_mapping: "./model/data/mapping-tables-model-empirical-filtered-augmented-ids.rds"


tables_dirichlet_filtered_augmented:
  dir_empiric: "./data/prolific/blockwords/filtered_data"
  tables_empiric: "./model/data/tables-dirichlet-filtered-with-augmented-toWPPL.rds"
  target_dir: "./model/results/tables-dirichlet-filtered-augmented"
  utts_path: "./model/data/utterances-dirichlet-filtered-tables.rds"
  target_fits: "params-fitted-dirichlet-filtered.csv"
  tables_mapping: "./model/data/mapping-tables-dirichlet-filtered-augmented-ids.rds"


tables_latent_mixture:
  tables_empiric: ""
  tables_mapping: ""
  target_dir: "./model/results/tables-latent-mixture"
  utts_path: "./model/data/utterances-latent-mixture-tables.rds"
  fits_ind: "latent-mixture-fits-ind-params.csv"
  fits_dep: "latent-mixture-fits-dep-params.csv"

## 2. Level configurations ##
# @arg utt: - if set to "p_delta" or "p_rooij", respective value must be
#           large (see in webppl file) for all states given to the speaker,
#           - if set to "" no condition, just sampled from prior as usual
speaker:
  bns_sampled: 1000
  level_max: "speaker"
  utt: ""
  target_fn: "results-speaker.rds"
  target_params: "params-speaker.rds"
  n_samples: 0 # bns given by empirical tables

prior:
  level_max: "prior"
  utt: ""
  target_fn: "results-prior.rds"
  target_params: "params-prior.rds"


priorN:
  level_max: "priorN"
  utt: ""
  target_fn: "results-priorN.rds"
  target_params: "params-priorN.rds"
  n_samples: 10000

ll:
  level_max: "LL"
  utt: "A > C"
  target_fn: "results-LL.rds"
  target_params: "params-LL-prior.rds"

pl:
  level_max: "PL"
  utt: "A > C"
  target_fn: "results-PL.rds"
  target_params: "params-prior-LL-PL.rds"


# to generate tables based on theoretic beta distributions
model_tables:
  n_ind_tables: 3000
  n_dep_tables: 2000
  indep_sigma: 0.005
  n_best_cns: 3

# match generated theoretic tables with all experimental data
model_input_all:
  target_dir: "./model/data"
  tables_path: "tables-model-empirical-all-with-augmented-toWPPL.rds"
  target_params: "params-tables-model-empirical-all-augmented.rds"
  target_mapping: "mapping-tables-model-empirical-all-augmented-ids.rds"
  
# match generated theoretic tables only with filtered experimental data
model_input_filtered:
  target_dir: "./model/data"
  tables_path: "tables-model-empirical-filtered-with-augmented-toWPPL.rds"
  target_params: "params-tables-model-empirical-filtered-augmented.rds"
  target_mapping: "mapping-tables-model-empirical-filtered-augmented-ids.rds"  

# there needs to be 1 blank final line!
